### ISSUE TITLE
Docker run issue - repository does not exist

### ISSUE THREAD

**Issue by xtiankisutsa** [leonjza/frida-boot#8]
The command docker.sh run, falls with the following error, on Docker version 20.10.7, build f0df350, running on MacOS Catalina 10.15.7.  

![Screenshot 2021-07-14 at 10 08 17](https://user-images.githubusercontent.com/7021125/125578807-904a3d15-0262-4486-81cc-c663a7dee3fa.png)

For some reason, the "docker.sh run" command was looking for the image 'security/frida-boot:latest' locally, which indeed does not exist. 

![image](https://user-images.githubusercontent.com/7021125/125579749-a9d301fa-8f23-42ea-b0d8-d5540c222153.png)

The fix for me, was to move the repository name i.e. leonjza/frida-boot, next to the container name like so:
docker run --cap-add SYS_PTRACE --rm -it --name frida-boot leonjza/frida-boot -p 9999:80 -v $(pwd)/code:/root/code 

This was a weird issue. Don't know if anyone else experienced it.

**Comment by leonjza** [comment]
That is so weird! I just tried locally and it seems to work fine? I know this is a silly question, but is your `docker.sh` modified somehow? 

![image](https://user-images.githubusercontent.com/1148127/125582544-a25d71ec-747e-4715-a6b4-28e669d79edb.png)
