### ISSUE TITLE
Fix docker.sh script for Linux users

### ISSUE THREAD

**Issue by IdanBanani** [leonjza/frida-boot#9]
Currently, trying to run the docker.sh on unix environment (like WSL2) will result in error message like:
`-bash: ./docker.sh: /bin/bash^M: bad interpreter: No such file or directory`

The fix is replacing the Dos chars with Unix ones.

`sed -i -e 's/\r$//' docker.sh`

EDIT: I think the reason it happend was due to using Github desktop cloning on Windows instead of CLI in WSL

**Comment by leonjza** [comment]
The file in the repo does not have Windows style line endings. A fresh clone on a pi as a test works fine as well.

![image](https://user-images.githubusercontent.com/1148127/135256051-eafc198d-7fe2-497c-9a8e-8754e0433c73.png)

The environment was not build with Windows in mind, but if you got it to work then great!
